### ISSUE TITLE
Module recreates resources on every run

### ISSUE THREAD

**Issue by soerenmartius** [mineiros-io/terraform-aws-cognito-user-pool#11]
It seems that we are not treating the default values in the right way. Setting nonexisting values to null will the recreation of some resources on every run.

<img width="1433" alt="Screenshot 2020-08-05 at 10 23 24" src="https://user-images.githubusercontent.com/930643/89389677-ff85f980-d705-11ea-9fc3-1a63a638480b.png">
<img width="1214" alt="Screenshot 2020-08-05 at 10 23 18" src="https://user-images.githubusercontent.com/930643/89389687-04e34400-d706-11ea-86f6-d0fcfa67407c.png">
<img width="1421" alt="Screenshot 2020-08-05 at 10 23 12" src="https://user-images.githubusercontent.com/930643/89389694-06ad0780-d706-11ea-8de4-b2027267e8d8.png">

**Comment by mariux** [comment]
@soerenmartius which version are you using?

**Comment by mariux** [comment]
https://github.com/mineiros-io/terraform-aws-cognito-user-pool/releases/tag/v0.1.1 should fix this behavior for string attributes..

**Comment by soerenmartius** [comment]
Still happening in v0.1.2. In addition to that,  some attributes such as `allowed_oauth_flows` are causing a recreation as well.
Since the unit tests are disabled, we didn't see it in the first place.

<img width="993" alt="Screenshot 2020-08-06 at 07 36 37" src="https://user-images.githubusercontent.com/930643/89495055-ba220480-d7b7-11ea-9a59-adab9b69018f.png">
<img width="1310" alt="Screenshot 2020-08-06 at 07 36 27" src="https://user-images.githubusercontent.com/930643/89495060-bc845e80-d7b7-11ea-9234-1acfb1f9343a.png">

**Comment by mariux** [comment]
please check if #13 fixes your issue....
